**Import Libraries**

In [1]:
import numpy as np

In [2]:
import pandas as pd

**Student IDs**

In [3]:
student_id = np.arange(1,101)

In [4]:
student_name = []
for i in range (1,101):
  student_name.append(f"student_name_{i}")
print(student_name[:5])

['student_name_1', 'student_name_2', 'student_name_3', 'student_name_4', 'student_name_5']

**Student Marks**

In [5]:
maths_marks=np.random.randint(35,100,100)
english_marks = np.random.randint(35,100,100)
science_mark = np.random.randint(35,100,100)

In [6]:

attendence = np.random.randint(85,100,100)

In [7]:
print(attendence[:20])

[88 87 88 95 89 86 87 89 97 93 86 91 97 94 98 96 99 93 90 85]

In [8]:
gender = np.random.choice(['Male','Female'],100)

In [9]:
student_dept = np.random.choice(['b.com','it','EEE','CSE','Tech'],100)
print(student_dept[:15])

['CSE' 'EEE' 'b.com' 'CSE' 'EEE' 'CSE' 'Tech' 'b.com' 'CSE' 'CSE' 'CSE'
 'Tech' 'Tech' 'EEE' 'EEE']

In [10]:
df=pd.DataFrame({'Student_Id': student_id, 'Name': student_name,'Gender': gender,'Dept':student_dept,'Maths': maths_marks,'English':english_marks,'Science':science_mark, 'Attendennce':attendence,De})

In [11]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce
0,1,student_name_1,Male,CSE,72,48,36,88
1,2,student_name_2,Female,EEE,73,39,63,87
2,3,student_name_3,Male,b.com,68,38,41,88
3,4,student_name_4,Female,CSE,80,44,85,95
4,5,student_name_5,Female,EEE,82,68,90,89
...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47,39,77,85
96,97,student_name_97,Female,Tech,73,62,74,88
97,98,student_name_98,Female,b.com,58,86,75,88
98,99,student_name_99,Male,it,61,62,52,95
99,100,student_name_100,Female,Tech,59,79,86,89

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_Id   100 non-null    int64
 1   Name         100 non-null    object
 2   Gender       100 non-null    object
 3   Dept         100 non-null    object
 4   Maths        100 non-null    int64
 5   English      100 non-null    int64
 6   Science      100 non-null    int64
 7   Attendennce  100 non-null    int64
dtypes: int64(5), object(3)
memory usage: 6.4+ KB

In [13]:
df.describe()

       Student_Id       Maths     English     Science  Attendennce
count  100.000000  100.000000  100.000000  100.000000   100.000000
mean    50.500000   68.870000   66.900000   66.180000    90.950000
std     29.011492   17.161535   18.486413   18.391028     4.495508
min      1.000000   35.000000   36.000000   35.000000    85.000000
25%     25.750000   55.000000   50.000000   51.750000    87.000000
50%     50.500000   68.000000   68.000000   66.500000    89.000000
75%     75.250000   84.250000   84.500000   82.250000    95.000000
max    100.000000   99.000000   95.000000   99.000000    99.000000

In [14]:
df['total']= (df['Maths']+df['English']+df['Science'])

In [15]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total
0,1,student_name_1,Male,CSE,72,48,36,88,156
1,2,student_name_2,Female,EEE,73,39,63,87,175
2,3,student_name_3,Male,b.com,68,38,41,88,147
3,4,student_name_4,Female,CSE,80,44,85,95,209
4,5,student_name_5,Female,EEE,82,68,90,89,240
...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47,39,77,85,163
96,97,student_name_97,Female,Tech,73,62,74,88,209
97,98,student_name_98,Female,b.com,58,86,75,88,219
98,99,student_name_99,Male,it,61,62,52,95,175
99,100,student_name_100,Female,Tech,59,79,86,89,224

In [16]:
df['Average']= df['total']/3

In [17]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average
0,1,student_name_1,Male,CSE,72,48,36,88,156,52.000000
1,2,student_name_2,Female,EEE,73,39,63,87,175,58.333333
2,3,student_name_3,Male,b.com,68,38,41,88,147,49.000000
3,4,student_name_4,Female,CSE,80,44,85,95,209,69.666667
4,5,student_name_5,Female,EEE,82,68,90,89,240,80.000000
...,...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47,39,77,85,163,54.333333
96,97,student_name_97,Female,Tech,73,62,74,88,209,69.666667
97,98,student_name_98,Female,b.com,58,86,75,88,219,73.000000
98,99,student_name_99,Male,it,61,62,52,95,175,58.333333
99,100,student_name_100,Female,Tech,59,79,86,89,224,74.666667

In [18]:
df['Grade']= np.where ( df['Average']>=90 ,'A',np.where (df['Average']>=75,'B', np.where (df['Average']>=50,'C','Fail')))

In [19]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
0,1,student_name_1,Male,CSE,72,48,36,88,156,52.000000,C
1,2,student_name_2,Female,EEE,73,39,63,87,175,58.333333,C
2,3,student_name_3,Male,b.com,68,38,41,88,147,49.000000,Fail
3,4,student_name_4,Female,CSE,80,44,85,95,209,69.666667,C
4,5,student_name_5,Female,EEE,82,68,90,89,240,80.000000,B
...,...,...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47,39,77,85,163,54.333333,C
96,97,student_name_97,Female,Tech,73,62,74,88,209,69.666667,C
97,98,student_name_98,Female,b.com,58,86,75,88,219,73.000000,C
98,99,student_name_99,Male,it,61,62,52,95,175,58.333333,C
99,100,student_name_100,Female,Tech,59,79,86,89,224,74.666667,C

In [20]:
Row_total = df[['English','Maths','Science']].sum(axis=1)
column_average = df[['English','Maths','Science']].mean(axis=0)

In [21]:
column_average

English    66.90
Maths      68.87
Science    66.18
dtype: float64

In [22]:
np.mean(df['Average'])
np.median(df['Average'])

np.float64(67.5)

In [23]:
np.max(df['Average'])
np.min(df['Average'])

39.666666666666664

In [24]:
top_student= df.sort_values(by='total',ascending=False)
top_student.head(10)

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
66,67,student_name_67,Male,CSE,93,86,95,93,274,91.333333,A
25,26,student_name_26,Male,EEE,91,94,84,87,269,89.666667,B
43,44,student_name_44,Male,EEE,99,78,92,85,269,89.666667,B
10,11,student_name_11,Female,CSE,77,95,96,86,268,89.333333,B
34,35,student_name_35,Male,CSE,72,90,99,87,261,87.000000,B
77,78,student_name_78,Male,EEE,86,76,99,86,261,87.000000,B
27,28,student_name_28,Female,CSE,82,86,87,87,255,85.000000,B
9,10,student_name_10,Female,CSE,87,70,97,93,254,84.666667,B
31,32,student_name_32,Male,b.com,73,87,88,88,248,82.666667,B
73,74,student_name_74,Female,Tech,85,83,78,89,246,82.000000,B

In [25]:
top_student

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
66,67,student_name_67,Male,CSE,93,86,95,93,274,91.333333,A
25,26,student_name_26,Male,EEE,91,94,84,87,269,89.666667,B
43,44,student_name_44,Male,EEE,99,78,92,85,269,89.666667,B
10,11,student_name_11,Female,CSE,77,95,96,86,268,89.333333,B
34,35,student_name_35,Male,CSE,72,90,99,87,261,87.000000,B
...,...,...,...,...,...,...,...,...,...,...,...
2,3,student_name_3,Male,b.com,68,38,41,88,147,49.000000,Fail
71,72,student_name_72,Male,CSE,55,50,42,85,147,49.000000,Fail
70,71,student_name_71,Female,it,39,60,44,93,143,47.666667,Fail
58,59,student_name_59,Female,EEE,49,40,52,90,141,47.000000,Fail
26,27,student_name_27,Female,CSE,36,39,44,86,119,39.666667,Fail

In [26]:
Stident_above_Avg = df[df['Average']>80]

In [27]:
Stident_above_Avg

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
5,6,student_name_6,Female,CSE,72,74,97,86,243,81.000000,B
9,10,student_name_10,Female,CSE,87,70,97,93,254,84.666667,B
10,11,student_name_11,Female,CSE,77,95,96,86,268,89.333333,B
23,24,student_name_24,Male,Tech,59,84,98,98,241,80.333333,B
25,26,student_name_26,Male,EEE,91,94,84,87,269,89.666667,B
27,28,student_name_28,Female,CSE,82,86,87,87,255,85.000000,B
28,29,student_name_29,Female,CSE,89,67,85,89,241,80.333333,B
31,32,student_name_32,Male,b.com,73,87,88,88,248,82.666667,B
34,35,student_name_35,Male,CSE,72,90,99,87,261,87.000000,B
43,44,student_name_44,Male,EEE,99,78,92,85,269,89.666667,B
66,67,student_name_67,Male,CSE,93,86,95,93,274,91.333333,A
73,74,student_name_74,Female,Tech,85,83,78,89,246,82.000000,B
76,77,student_name_77,Female,EEE,79,84,82,86,245,81.666667,B
77,78,student_name_78,Male,EEE,86,76,99,86,261,87.000000,B
86,87,student_name_87,Female,it,84,93,65,88,242,80.666667,B

In [28]:
Dept_Avg = df.groupby('Dept')['Average'].mean()
Dept_Avg

Dept
CSE      70.027778
EEE      69.507246
Tech     64.777778
b.com    65.562500
it       65.187500
Name: Average, dtype: float64

In [29]:
Gender_Average = df.groupby('Gender')['Average'].mean()
Gender_Average

Gender
Female    67.713450
Male      66.790698
Name: Average, dtype: float64

In [30]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
0,1,student_name_1,Male,CSE,72,48,36,88,156,52.000000,C
1,2,student_name_2,Female,EEE,73,39,63,87,175,58.333333,C
2,3,student_name_3,Male,b.com,68,38,41,88,147,49.000000,Fail
3,4,student_name_4,Female,CSE,80,44,85,95,209,69.666667,C
4,5,student_name_5,Female,EEE,82,68,90,89,240,80.000000,B
...,...,...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47,39,77,85,163,54.333333,C
96,97,student_name_97,Female,Tech,73,62,74,88,209,69.666667,C
97,98,student_name_98,Female,b.com,58,86,75,88,219,73.000000,C
98,99,student_name_99,Male,it,61,62,52,95,175,58.333333,C
99,100,student_name_100,Female,Tech,59,79,86,89,224,74.666667,C

In [31]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
0,1,student_name_1,Male,CSE,72,48,36,88,156,52.000000,C
1,2,student_name_2,Female,EEE,73,39,63,87,175,58.333333,C
2,3,student_name_3,Male,b.com,68,38,41,88,147,49.000000,Fail
3,4,student_name_4,Female,CSE,80,44,85,95,209,69.666667,C
4,5,student_name_5,Female,EEE,82,68,90,89,240,80.000000,B
...,...,...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47,39,77,85,163,54.333333,C
96,97,student_name_97,Female,Tech,73,62,74,88,209,69.666667,C
97,98,student_name_98,Female,b.com,58,86,75,88,219,73.000000,C
98,99,student_name_99,Male,it,61,62,52,95,175,58.333333,C
99,100,student_name_100,Female,Tech,59,79,86,89,224,74.666667,C

In [32]:
df['Name'] = df['Name'].replace('student_name_2', np.nan)
df['Maths'] = df['Maths'].replace(79, np.nan)
df['Maths'] = df['Maths'].replace(91, np.nan)
df['English'] = df['English'].replace(84, np.nan)
df['English'] = df['English'].replace(90, np.nan)
df['Science'] = df['Science'].replace(52, np.nan)
df['Science'] = df['Science'].replace(62, np.nan)

In [33]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
0,1,student_name_1,Male,CSE,72.0,48.0,36.0,88,156,52.000000,C
1,2,NaN,Female,EEE,73.0,39.0,63.0,87,175,58.333333,C
2,3,student_name_3,Male,b.com,68.0,38.0,41.0,88,147,49.000000,Fail
3,4,student_name_4,Female,CSE,80.0,44.0,85.0,95,209,69.666667,C
4,5,student_name_5,Female,EEE,82.0,68.0,90.0,89,240,80.000000,B
...,...,...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47.0,39.0,77.0,85,163,54.333333,C
96,97,student_name_97,Female,Tech,73.0,62.0,74.0,88,209,69.666667,C
97,98,student_name_98,Female,b.com,58.0,86.0,75.0,88,219,73.000000,C
98,99,student_name_99,Male,it,61.0,62.0,NaN,95,175,58.333333,C
99,100,student_name_100,Female,Tech,59.0,79.0,86.0,89,224,74.666667,C

In [34]:
df.isnull().sum()

Student_Id     0
Name           1
Gender         0
Dept           0
Maths          3
English        4
Science        5
Attendennce    0
total          0
Average        0
Grade          0
dtype: int64

In [35]:
df['Maths']=df['Maths'].fillna(df['Maths'].mean())


# df['Math'] = df['Math'].fillna(df['Math'].mean())

In [36]:
mean_maths= df['Maths'].mean()
mean_maths

np.float64(68.30927835051546)

In [37]:
df['Maths']=df['Maths'].fillna(mean_maths)

In [38]:
mean_english= df['English'].mean()
df['English']= df['English'].fillna(mean_english)

In [39]:
mean_science= df['Science'].mean()
df['Science']=df['Science'].fillna(mean_science)

In [40]:
df.isnull().sum()

Student_Id     0
Name           1
Gender         0
Dept           0
Maths          0
English        0
Science        0
Attendennce    0
total          0
Average        0
Grade          0
dtype: int64

In [41]:
df['Name']=df['Name'].fillna('student_name_2')

In [42]:
df

,Student_Id,Name,Gender,Dept,Maths,English,Science,Attendennce,total,Average,Grade
0,1,student_name_1,Male,CSE,72.0,48.0,36.000000,88,156,52.000000,C
1,2,student_name_2,Female,EEE,73.0,39.0,63.000000,87,175,58.333333,C
2,3,student_name_3,Male,b.com,68.0,38.0,41.000000,88,147,49.000000,Fail
3,4,student_name_4,Female,CSE,80.0,44.0,85.000000,95,209,69.666667,C
4,5,student_name_5,Female,EEE,82.0,68.0,90.000000,89,240,80.000000,B
...,...,...,...,...,...,...,...,...,...,...,...
95,96,student_name_96,Male,Tech,47.0,39.0,77.000000,85,163,54.333333,C
96,97,student_name_97,Female,Tech,73.0,62.0,74.000000,88,209,69.666667,C
97,98,student_name_98,Female,b.com,58.0,86.0,75.000000,88,219,73.000000,C
98,99,student_name_99,Male,it,61.0,62.0,66.821053,95,175,58.333333,C
99,100,student_name_100,Female,Tech,59.0,79.0,86.000000,89,224,74.666667,C

In [43]:
df.isnull().sum()

Student_Id     0
Name           0
Gender         0
Dept           0
Maths          0
English        0
Science        0
Attendennce    0
total          0
Average        0
Grade          0
dtype: int64

In [44]:
df[df.duplicated()]

Empty DataFrame
Columns: [Student_Id, Name, Gender, Dept, Maths, English, Science, Attendennce, total, Average, Grade]
Index: []

In [45]:
df.to_csv('Student_Performance_Analysis.csv',index=False)

In [46]:
print('Total_Student:', len(df))
print('Highest Total:',np.max(df['total']))
print('Lowest Total:',np.min(df['total']))
print('Average_Total:',np.average(df['total']))

Total_Student: 100
Highest Total: 274
Lowest Total: 119
Average_Total: 201.95